### ISSUE TITLE
Problem importing sncosmo

### ISSUE THREAD

**Issue by adamjstewart** [sncosmo/sncosmo#137]
Hello, I'm trying to install sncosmo and am running into trouble. Here are the dependencies and versions I have installed:

- Python 2.7.11
- Astropy 1.1.2
- Scipy 0.17.0
- Numpy 1.11.0
- Matplotlib 1.4.3
- Emcee 2.1.0
- Iminuit 1.2
- Nestle 0.1.1

I'm seeing this error message when trying to import it:

```python
$ python
Python 2.7.11 (default, May 25 2016, 10:46:39) 
[GCC 6.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> import scipy
>>> import numpy
>>> import matplotlib
>>> import emcee
>>> import iminuit
>>> import nestle
>>> import sncosmo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/soft/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-2.7.11-s2pds3mtnxhisxlplc3ut6uuj3yn3miq/lib/python2.7/site-packages/sncosmo-1.2.0-py2.7-linux-x86_64.egg/sncosmo/__init__.py", line 156, in <module>
    from .dustmap import *
  File "/soft/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-2.7.11-s2pds3mtnxhisxlplc3ut6uuj3yn3miq/lib/python2.7/site-packages/sncosmo-1.2.0-py2.7-linux-x86_64.egg/sncosmo/dustmap.py", line 8, in <module>
    from astropy.coordinates import SkyCoord
  File "/soft/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-2.7.11-s2pds3mtnxhisxlplc3ut6uuj3yn3miq/lib/python2.7/site-packages/astropy-1.1.2-py2.7-linux-x86_64.egg/astropy/coordinates/__init__.py", line 13, in <module>
    from .baseframe import *
  File "/soft/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-2.7.11-s2pds3mtnxhisxlplc3ut6uuj3yn3miq/lib/python2.7/site-packages/astropy-1.1.2-py2.7-linux-x86_64.egg/astropy/coordinates/baseframe.py", line 1181, in <module>
    from .earth import EarthLocation
  File "/soft/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-2.7.11-s2pds3mtnxhisxlplc3ut6uuj3yn3miq/lib/python2.7/site-packages/astropy-1.1.2-py2.7-linux-x86_64.egg/astropy/coordinates/earth.py", line 440, in <module>
    from .sites import get_builtin_sites, get_downloaded_sites
ImportError: No module named sites
>>> 
```

As you can see, all of the dependencies are present and import successfully. Is there an undocumented dependency I'm missing? Are there any build tests that I can run to diagnose the problem? I can provide build logs if you want.

**Comment by kbarbary** [comment]
From the traceback, looks like there's a problem with the astropy install (the `sites.py` file in `astropy/coordinates` seems to be missing). Note that `import astropy` doesn't actually import most subpackages (same thing with scipy), so it is not a good test that astropy is properly installed.

**Comment by adamjstewart** [comment]
Ah, you're right. Thanks for the help!
