### ISSUE TITLE
unable to use vega magsystem

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#174]
The following code

import sncosmo

model = sncosmo.Model(source='salt2')
print model.bandmag('desi','vega',0.)

returns an error

251:gerard akim$ ./temp.py 
Traceback (most recent call last):
  File "./temp.py", line 5, in <module>
    print model.bandmag('desi','vega',0.)
  File "/Users/akim/anaconda2/lib/python2.7/site-packages/sncosmo/models.py", line 1502, in bandmag
    return _bandmag(self, band, magsys, time)
  File "/Users/akim/anaconda2/lib/python2.7/site-packages/sncosmo/models.py", line 196, in _bandmag
    ms = get_magsystem(ms)
  File "/Users/akim/anaconda2/lib/python2.7/site-packages/sncosmo/magsystems.py", line 23, in get_magsystem
    return _MAGSYSTEMS.retrieve(name)
  File "/Users/akim/anaconda2/lib/python2.7/site-packages/sncosmo/_registry.py", line 162, in retrieve
    self._instances[key] = func(*args, name=name)
  File "/Users/akim/anaconda2/lib/python2.7/site-packages/sncosmo/builtins.py", line 235, in load_spectral_magsys_fits
    abspath = get_abspath(relpath, name)
  File "/Users/akim/anaconda2/lib/python2.7/site-packages/sncosmo/builtins.py", line 101, in get_abspath
    url = get_url(name, version)
  File "/Users/akim/anaconda2/lib/python2.7/site-packages/sncosmo/builtins.py", line 51, in get_url
    urls = json.load(reader(f))
  File "/Users/akim/anaconda2/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Users/akim/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/akim/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/akim/anaconda2/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 84 column 1 (char 7223)

**Comment by kbarbary** [comment]
Thanks for reporting. There was an error in a file that sncosmo downloads. It should be fixed now. Try again?

**Comment by AlexGKim** [comment]
Works now.  Thanks!
