### ISSUE TITLE
`'desz'` band import failure but recognized in registry bandpass list.

### ISSUE THREAD

**Issue by cnsetzer** [sncosmo/sncosmo#210]
I am using sncosmo 1.5.1, with python 3.6.3 (astropy 2.0.2 and numpy 1.13.3). Currently when I import most bandpass filters they work correctly, but specifically the `'desz'` band is failing. Here is an example of what is happening, with the Traceback message.
```
>>> import sncosmo
>>> sncosmo.get_bandpass('desg')
<Bandpass 'desg' at 0x1045b9358>
>>> sncosmo.get_bandpass('desz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/sncosmo/bandpasses.py", line 27, in get_bandpass
    return _BANDPASSES.retrieve(name)
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/sncosmo/_registry.py", line 162, in retrieve
    self._instances[key] = func(*args, name=name)
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/sncosmo/builtins.py", line 77, in load_bandpass_remote_aa
    trim_level=BANDPASS_TRIM_LEVEL, name=name)
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/sncosmo/bandpasses.py", line 73, in read_bandpass
    trim_level=trim_level, name=name)
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/sncosmo/bandpasses.py", line 201, in __init__
    s = slice_exclude_below(trans, np.max(trans) * trim_level, grow=1)
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2272, in amax
    out=out, **kwargs)
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity 
```

For reference, if I attempt to access, a band that is not in the list, I get the following different message. (Note: it can be seen that `'desz'` is indeed in the bandpass list.)

```
>>> sncosmo.get_bandpass('desgr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/sncosmo/bandpasses.py", line 27, in get_bandpass
    return _BANDPASSES.retrieve(name)
  File "/Users/cnsetzer/miniconda3/envs/snmachine3/lib/python3.6/site-packages/sncosmo/_registry.py", line 194, in retrieve
    .format(name, "', '".join(registered_names)))
Exception: 'desgr' not in registry. Registered names: 'uvf775w', 'f606w', 'swope2::i', 'keplercam::r', 'sdss::r', 'f444w', 'keplercam::us', 'swope2::y', 'swope2::v', 'sdss::g', 'f139m', 'cspr', 'f625w', 'f1140c', '4shooter2::i', 'nicf160w', 'f2300c', 'swope2::b', 'sdssi', 'f300x', 'f335m', 'standard::b', 'f410m', 'f360m', 'f763m', '4shooter2::us', 'acswf::f606w', 'sdssg', 'uvf850lp', 'lsstz', 'sdss::z', 'lsstg', 'swope2::u', 'keplercam::v', 'swope2::h', 'f218w', 'sdssu', 'acswf::f850lp', 'cspjs', 'cspv3014', 'standard::r', 'cspu', 'cspv9844', 'f277w', '4shooter2::r', 'acswf::f775w', 'f336w', 'cspv3009', 'csphd', 'f140w', 'uvf814w', 'keplercam::b', 'lsstr', 'bessellb', 'f555w', 'f1500w', 'f105w', 'f689m', 'f225w', 'nicf110w', 'f1800w', 'lssty', 'cspjd', 'bessellv', 'swope2::v2', 'keplercam::i', 'standard::i', 'kepler', 'nicmos2::f110w', 'desr', 'f140m', 'swope2::g', 'f115w', 'sdss::i', 'f275w', 'standard::u', 'f182m', 'f460m', 'nicmos2::f160w', 'f2550w', 'f1065c', 'swope2::v1', 'f150w', 'f098m', 'desz', 'f125w', 'f160w', 'f850lp', 'f356w', 'f560w', 'sdssz', 'lsstu', 'uvf555w', 'f1550c', 'f1000w', 'standard::v', 'uvf606w', 'cspys', 'f770w', 'f300m', 'bessellr', 'f1280w', 'swope2::j', 'sdssr', 'f845m', '4shooter2::b', 'f2100w', '4shooter2::v', 'f1130w', 'csphs', 'f438w', 'besselli', 'f775w', 'bessellux', 'f350lp', 'uvf625w', 'f090w', 'f127m', 'cspi', 'f250m', 'lssti', 'desg', 'f430m', 'desy', 'f390w', 'f110w', 'f162m', 'sdss::u', 'cspb', 'f070w', 'f480m', 'cspk', 'cspg', 'f153m', 'uvf475w', 'f475w', 'desi', 'swope2::r', 'cspyd', 'f435w', 'f210m', 'f200w' 
```

**Comment by kbarbary** [comment]
I'm not completely sure, but this *might* be due to a bug that was fixed on master in #206. The bug has to do with an empty data file being created when a previous download attempt failed.

To check, can you try deleting the file `bandpasses/des/des_z.dat` in the sncosmo data directory, then try it again? By default the data directory is `$HOME/.astropy/cache/sncosmo`.

**Comment by cnsetzer** [comment]
That worked! Thanks for the help.

**Comment by kbarbary** [comment]
Great! I should do a 1.5.2 release with the fix soon.
