### ISSUE TITLE
No module named 'sncosmo.salt2utils'

### ISSUE THREAD

**Issue by rebekah9969** [sncosmo/sncosmo#226]
I am having an issue with installing sncosmo from source in order to get the new SNEMO models. 
When I try to install I get the following issue..

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hounsell/sncosmo/sncosmo/__init__.py", line 136, in <module>
    from .models import *
  File "/Users/hounsell/sncosmo/sncosmo/models.py", line 27, in <module>
    from .salt2utils import BicubicInterpolator, SALT2ColorLaw
ImportError: No module named 'sncosmo.salt2utils'

I have tried removing sncosmo and re-installing several times. Each time with the same issue. 
I have worked through all steps outlined here,
#195

**Comment by kbarbary** [comment]
It looks like the source directory(`/Users/hounsell/sncosmo`) is being picked up first when you import sncosmo. This is a problem  because the cython extension is not built in the source directory. Two options are:

- Run `setup.py develop`. This builds the cython extensions in the source directory.

- Add the build directory to your PYTHONPATH and use setup.py build:
  ```bash
  export PYTHONPATH=/Users/hounsell/sncosmo/build/lib.linux-x86_64-3.6:$PYTHONPATH
  setup.py build
  ```

**Comment by rebekah9969** [comment]
Thank you very much. It now works.
